# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATROM_PLUGIN_PATH'] =  "../platfroms"
class Ui_CaesarCipher(object):
    def setupUi(self, CaesarCipher):
        CaesarCipher.setObjectName("CaesarCipher")
        CaesarCipher.resize(800, 600)
        CaesarCipher.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(CaesarCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.lblPlainText = QtWidgets.QLabel(self.centralwidget)
        self.lblPlainText.setGeometry(QtCore.QRect(40, 110, 47, 13))
        self.lblPlainText.setObjectName("lblPlainText")
        self.lblKey = QtWidgets.QLabel(self.centralwidget)
        self.lblKey.setGeometry(QtCore.QRect(50, 210, 47, 13))
        self.lblKey.setObjectName("lblKey")
        self.lblCipherText = QtWidgets.QLabel(self.centralwidget)
        self.lblCipherText.setGeometry(QtCore.QRect(50, 290, 47, 13))
        self.lblCipherText.setObjectName("lblCipherText")
        self.EncryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.EncryptButton.setGeometry(QtCore.QRect(160, 430, 75, 23))
        self.EncryptButton.setObjectName("EncryptButton")
        self.DecryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.DecryptButton.setGeometry(QtCore.QRect(320, 430, 75, 23))
        self.DecryptButton.setObjectName("DecryptButton")
        self.PlainTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.PlainTextEdit.setGeometry(QtCore.QRect(140, 80, 321, 71))
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.CipherTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.CipherTextEdit.setGeometry(QtCore.QRect(140, 260, 321, 71))
        self.CipherTextEdit.setObjectName("CipherTextEdit")
        self.KeyEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.KeyEdit.setGeometry(QtCore.QRect(140, 200, 321, 20))
        self.KeyEdit.setObjectName("KeyEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 40, 301, 16))
        self.label_2.setObjectName("label_2")
        CaesarCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaesarCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        CaesarCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaesarCipher)
        self.statusbar.setObjectName("statusbar")
        CaesarCipher.setStatusBar(self.statusbar)

        self.retranslateUi(CaesarCipher)
        QtCore.QMetaObject.connectSlotsByName(CaesarCipher)

    def retranslateUi(self, CaesarCipher):
        _translate = QtCore.QCoreApplication.translate
        CaesarCipher.setWindowTitle(_translate("CaesarCipher", "Caesar Cipher-caesar.ui"))
        self.label.setText(_translate("CaesarCipher", "                   CAESAR CIPHER"))
        self.lblPlainText.setText(_translate("CaesarCipher", "PlainText"))
        self.lblKey.setText(_translate("CaesarCipher", "Key"))
        self.lblCipherText.setText(_translate("CaesarCipher", "CipherText"))
        self.EncryptButton.setText(_translate("CaesarCipher", "Encrypt"))
        self.DecryptButton.setText(_translate("CaesarCipher", "Decrypt"))
        self.label_2.setText(_translate("CaesarCipher", "Nguyen bao sang-2280602711"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaesarCipher = QtWidgets.QMainWindow()
    ui = Ui_CaesarCipher()
    ui.setupUi(CaesarCipher)
    CaesarCipher.show()
    sys.exit(app.exec_())
